/* eslint-disable jsx-a11y/anchor-is-valid */
import Head from 'next/head'
import Link from 'next/link'
import React, { ReactNode } from 'react'

import { PageProps } from '../../../pages/[[...slug]]'
import { Footer, Header, Main } from '../../organisms'

const PreviewBanner = () => (
  <div className="w-full p-2 text-center">
    <Link href="/api/clear-preview">
      <a>Preview mode | Click to exit</a>
    </Link>
  </div>
)

type LayoutProps = Omit<PageProps, 'slug'> & {
  children?: ReactNode
}

export const Layout = ({
  children,
  footer,
  header,
  isPreview,
  title,
}: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      {isPreview && <PreviewBanner />}
      <Header {...header} />
      <Main>{children}</Main>
      <Footer {...footer} />
    </>
  )
}
