import type { NextPage } from 'next'

import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <h1 className="font-JetBrainsMono text-2xl font-light">
        Synsisal® - Sisal Without Limits
      </h1>
      <h1 className="font-JetBrainsMono text-2xl font-normal">
        Synsisal® - Sisal Without Limits
      </h1>
      <main className="font-JetBrainsMono text-2xl font-medium">main</main>
      <footer className="font-JetBrainsMono text-2xl font-semibold">
        footer
      </footer>
    </div>
  )
}

export default Home
