import type { NextPage } from 'next'

import Head from 'next/head'

import { getEntries } from '../services'

export const getServerSideProps = async () => {
  const entries = await getEntries({
    content_type: 'recipe',
    'fields.slug': 'ceviche',
    include: 10,
  })

  if (entries) {
    return { props: entries }
  }

  return { props: null }
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <header className="font-JetBrainsMono text-2xl font-normal">
        Header
      </header>
      <main className="font-JetBrainsMono text-2xl font-medium">Main</main>
      <footer className="font-JetBrainsMono text-2xl font-semibold">
        Footer
      </footer>
    </div>
  )
}

export default Home
