import type { NextPage } from 'next'

import Head from 'next/head'

import { Home } from '../components/templates'
import { getEntries } from '../services'

export const getServerSideProps = async () => {
  const entries = await getEntries({
    content_type: 'recipe',
    'fields.slug': 'ceviche',
    include: 10,
  })

  if (entries) {
    return { props: entries }
  }

  return { props: null }
}

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Home />
    </>
  )
}

export default HomePage
